# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  docker-publish: circleci/docker-publish@0.1.6

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: rundeck/ci@sha256:85ce247940c39bcb77794778c2b7aa02feabfa1a37036b88942bc0c1235495f2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      GRADLE_OPTS: -Xmx1024m -XX:MaxPermSize=192m
      _JAVA_OPTIONS: "-Xmx1024m"
      TERM: dumb
      BASH_ENV: ~/.bash_profile

    steps:
      - checkout
      - setup_remote_docker
      - run: ./gradlew --no-daemon --max-workers 2 -x check install --stacktrace --info
      - run: groovy testbuild.groovy --buildType=development
      - run: make ENV=development rpm deb
      - docker-publish/check
      - run: ./gradlew docker:officialPush
